version: "2"
services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /var/www/html:/var/www/html
        links:
            - zyara.sh
            - halcyon
            - sqrwav
            - zyshara.me

    zyara.sh:
        container_name: zyara.sh
        build:
            args:
                - GIT_REPO=git@github.com:zyarash/zyara.sh.git
            context: .
            dockerfile: nodejs.Dockerfile
        expose:
            - "3000"

    halcyon:
        container_name: halcyon
        build:
            args:
                - GIT_REPO=git@github.com:zyarash/halcyon.git
            context: .
            dockerfile: nodejs.Dockerfile
        expose:
            - "3000"

    sqrwav:
        container_name: sqrwav
        build:
            args:
                - GIT_REPO=git@github.com:zyarash/sqrwav.git
            context: .
            dockerfile: nodejs.Dockerfile
        expose:
            - "3000"

    zyshara.me:
        container_name: zyshara.me
        build:
            args:
                - GIT_REPO=git@github.com:zyarash/zyshara.me.git
            context: .
            dockerfile: nodejs.Dockerfile
        expose:
            - "3000"

    cutiecacti.me:
        container_name: cutiecacti.me
        build:
            args:
                - GIT_REPO=git@github.com:zyarash/cutiecacti.me.git
            context: .
            dockerfile: nodejs.Dockerfile
        expose:
            - "3000"

networks:
    default:
        external:
            name: language
